CREATE DATABASE revvo;
USE revvo;

-- Tabela de Anexo
CREATE TABLE anexo_curso (
    ID_ANEXO_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CURSO INT NOT NULL,                    
    NOME VARCHAR(100) NULL,
    TIPO VARCHAR(50) NULL,
    TAMANHO INT DEFAULT 0,
    ARQUIVO MEDIUMBLOB NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CURSO_ANEXO FOREIGN KEY (ID_CURSO) REFERENCES curso(ID_CURSO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabela de Curso
CREATE TABLE curso (
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NULL,
    DESCRICAO VARCHAR(500) NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
