CREATE DATABASE revvo;
USE revvo;

CREATE TABLE imagem_curso (
    ID_IMAGEM_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NULL,
    TIPO VARCHAR(50) NULL,
    ARQUIVO MEDIUMBLOB NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE curso (
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NULL,
    DESCRICAO VARCHAR(500) NULL,
    ID_IMAGEM_CURSO INT NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CURSO_IMAGEM FOREIGN KEY (ID_IMAGEM_CURSO) REFERENCES imagem_curso(ID_IMAGEM_CURSO) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
