create database revvo;
use revvo;

CREATE TABLE curso (
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NULL,
    DESCRICAO VARCHAR(500) NULL,
    IMAGEM MEDIUMBLOB NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;